version: "3.7"
services:
  postgres:
    image: postgres:12.4
    restart: always
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: test-simoh
      POSTGRES_PASSWORD: test-simoh
      POSTGRES_DB: test-simoh
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front-end:
    build: './front/'
    restart: unless-stopped
    volumes:
      - './front:/app'
      - 'front-node_modules:/app/node_modules'
    ports:
      - "3030:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  back-end:
    build: './api/'
    restart: unless-stopped
    volumes:
      - './api:/app'
      - 'api-node_modules:/app/node_modules'
    ports:
      - "4000:4000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  front-node_modules:
  api-node_modules:

